/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentaltoolkit.Frame;

import Controlador.Paciente;
import Validaciones.Validador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EHef_
 */
public class AgregarPaciente extends javax.swing.JPanel {

    /**
     * Creates new form RegistroAdmin
     */
    public AgregarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        CAMPONOMBRE = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CAMPOAM = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        CAMPOAP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CAMPOCEL = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CAMPOCORREO = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        CAMPOCASA = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CAMPOPADECIEMIENTO = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("APELLIDO MATERNO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 890, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREAR PACIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 230, 50));

        CAMPONOMBRE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPONOMBRE.setBorder(null);
        CAMPONOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPONOMBREActionPerformed(evt);
            }
        });
        jPanel1.add(CAMPONOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 330, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 330, 10));

        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("NOMBRES");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 270, 10));

        CAMPOAM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOAM.setBorder(null);
        CAMPOAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPOAMActionPerformed(evt);
            }
        });
        jPanel1.add(CAMPOAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 230, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 230, 10));

        CAMPOAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOAP.setBorder(null);
        jPanel1.add(CAMPOAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 230, 30));

        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("APELLIDO PATERNO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        CAMPOCEL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOCEL.setBorder(null);
        CAMPOCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPOCELActionPerformed(evt);
            }
        });
        jPanel1.add(CAMPOCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 410, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 410, 10));

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("PADECIMIENTOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        CAMPOCORREO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOCORREO.setBorder(null);
        jPanel1.add(CAMPOCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 410, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 410, 10));

        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("CORREO ELECTRONICO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        CAMPOCASA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAMPOCASA.setBorder(null);
        jPanel1.add(CAMPOCASA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 410, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 410, 10));

        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("TELEFONO CASA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("NÚMERO CELULAR");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        CAMPOPADECIEMIENTO.setColumns(20);
        CAMPOPADECIEMIENTO.setRows(5);
        jScrollPane1.setViewportView(CAMPOPADECIEMIENTO);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 410, 110));

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 140, 50));

        jButton2.setText("ACEPTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 140, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void CAMPOAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPOAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPOAMActionPerformed

    private void CAMPOCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPOCELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPOCELActionPerformed

    private void CAMPONOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPONOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPONOMBREActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Paciente Pa= new Paciente();
        Validador Va = new Validador();
        if(Va.ValidaCel(CAMPOCEL.getText())){
            if(Va.ValidaTel(CAMPOCASA.getText())){
                if(Va.validateEMAIL(CAMPOCORREO.getText())){
                    int a=0;
                    try {
                        a=Pa.CrearPaciente(CAMPONOMBRE.getText(),CAMPOAP.getText()+ " "+CAMPOAM.getText(),CAMPOPADECIEMIENTO.getText(),CAMPOCEL.getText(),CAMPOCORREO.getText(),CAMPOCASA.getText(),"3");
                    } catch (SQLException ex) {
                        Logger.getLogger(AgregarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(a==1){
                        JOptionPane.showMessageDialog(this, "¡Paciente agregado!");
                    }else{
                        JOptionPane.showMessageDialog(this, "¡Paciente duplicado!");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "¡Correo invalido!");
                }
            }else{
                JOptionPane.showMessageDialog(this, "¡Numero de casa invalido!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "¡Numero de celualr invalido!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAMPOAM;
    private javax.swing.JTextField CAMPOAP;
    private javax.swing.JTextField CAMPOCASA;
    private javax.swing.JTextField CAMPOCEL;
    private javax.swing.JTextField CAMPOCORREO;
    private javax.swing.JTextField CAMPONOMBRE;
    private javax.swing.JTextArea CAMPOPADECIEMIENTO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
